---
title: "557_Project_2BS"
author: "Ben Straub, Hillary Koch, Jiawei Huang, Arif Masrur"
date: "3/15/2017"
output: pdf_document
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
### Testing out Github
rm(list=ls())
par(mfrow=c(1,1))
# Loading packages into R
library(data.table);library(car);library(lars);library(knitr);library(ISLR);library(leaps);library(glmnet);library(MASS);library(reshape)

setwd("/Users/benStraub/Desktop/557/Project 2")
seismic <- read.csv("seismic.csv")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, comment=NA}
# EDA
names(seismic)
summary(seismic)
# Correlation Plot of the data...7 variables removed
source("http://www.sthda.com/upload/rquery_cormat.r")
x <- seismic[c(-1,-2,-3,-8,-14,-15,-16,-19)]
require("corrplot")
rquery.cormat(x)       
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
### Making nice and pretty

### Dropping seismic for now...maybe should be our focus
seismic <- seismic[,-2]

### Focus on "Seismoacoustic" and renaming to y...so I don't have to type it!!
seismic <- rename(seismic, c(seismic="y.train"))

#2584x19 matrix
n=dim(seismic)[1]
p=dim(seismic)[2]

# Setting up 
set.seed(2016)
test=sample(n, round(n/4))

### Seperating data into Test and Training Sets
# Train
y.train <- seismic$y[-test]
X.train <- seismic[-test,]

# Test
y.test <- seismic$y[test]
X.test <- seismic[test,]

### Training Data Matrix
### 1938 obs in Training Set
seismic.train <- as.data.frame(cbind(y.train,X.train))
seismic.train <- seismic.train[,-2]

### Testing Data Matrix
### 646 obs in Test Set
seismic.test <- as.data.frame(cbind(y.test, X.test))
seismic.test <- seismic.test[,-2]

#View(seismic.train)
#View(seismic.test)
```


```{r}

############# LOGISTIC REGRESSION ###################

### Training Set on Logistic Regression
glm.fit=glm(y.train~., data=seismic.train ,family=binomial)
summary(glm.fit)
glm.probs=predict(glm.fit ,type="response")
glm.probs[1:10]
contrasts(seismic.train$y.train)

glm.pred=rep("a",1938)
glm.pred[glm.probs >.5]="b"
table(glm.pred ,y.train)
mean(glm.pred==y.train)

### Testing Set on Logistic Regression
glm.fit=glm(y.test~., data=seismic.test ,family=binomial)
glm.probs=predict(glm.fit, type="response")

glm.pred=rep("a",646)
glm.pred[glm.probs >.5]="b"
table(glm.pred, y.test)
mean(glm.pred==y.test)
```
